### ISSUE TITLE
执行npm run release报错

### ISSUE THREAD

**Issue by akliyiping** [cipchk/delon#148]
- ng-delon version: 1.4.0 master分支
- node version: 9.11.1
- npm version: 6.4.1
- macOS version: 10.13.6
## 【必填项】重现链接，Reproduction link
https://ng-alain.com/docs/contributing
参考delon 基建类库

## 重现步骤，Steps to reproduce
执行npm run release 构建 packages 发布包时报错
错误如下：

npm run release
> delon@1.4.0 release /Users/eric/work/IdeaProjects/open/my-delon
> bash ./build.sh && bash build-schematics.sh -b

./build.sh: line 1: ﻿#!/usr/bin/env: No such file or directory
=====BUILDING: Version 1.4.0, Zorro Version ^1.4.1
====== Copy source [exclude: schematics]
====== BUNDLING acl
======    VERSION: Updating version references in /Users/eric/work/IdeaProjects/open/my-delon/dist/packages/acl
======    Compiling to es2015 via Angular compiler
======    Bundling to es module of es2015
Unexpected key 'output' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
Error: Unexpected key 'output' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, onwarn, outro, plugins, sourceMap
    at validateKeys (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/src/utils/validateKeys.js:12:11)
    at Object.rollup (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/src/rollup.js:39:16)
    at bundle (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/bin/runRollup.js:136:16)
    at execute (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/bin/runRollup.js:125:3)
    at /Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/bin/runRollup.js:69:4
    at tryCatch (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:185:12)
    at invokeCallback (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:197:13)
    at publish (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:168:7)
    at flush (/Users/eric/work/IdeaProjects/open/my-delon/node_modules/fmin/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:87:5)
    at process._tickCallback (internal/process/next_tick.js:176:11)
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! delon@1.4.0 release: `bash ./build.sh && bash build-schematics.sh -b`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the delon@1.4.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by akliyiping** [comment]
解决了，yarn 之后，node_modules/.bin 下面的rollup版本不知道为啥给我装成0.25.8了，换成0.58.2解决
