### ISSUE TITLE
yarn global 安装 @delon/cli 可以免除手动复制和手动安装devkit等依赖

### ISSUE THREAD

**Issue by PMExtra** [cipchk/delon#60]
如题，在
MacOS 10.13.4
Node 8.11.1
Npm 6.0.0
Yarn 1.6.0
新安装纯净环境下实测，只需要

```
yarn global add @angular/cli
yarn global add @delon/cli
ng new -c=@delon/cli my-app
```

就可以用了，完全不需要手动安装 @angular-devkit/core @angular-devkit/schematics @schematics/schematics rxjs typescript 等一大堆全局依赖包，也不需要手动复制 @delon 到 @angular/cli/node_modules

建议更新文档推荐大家采用这种方式安装 @delon/cli ，我被npm/cnpm坑了几个小时才终于找到还能这么玩。

**Comment by cipchk** [comment]
亲测的确可行，Mac 10.13.3

**Comment by fhq** [comment]
win/linux
测试都不行~

**Comment by siroccox** [comment]
windows10 测试通过

**Comment by MissHoya** [comment]
报错：
Schematic "ng-new" not found in collection "@delon/cli".

**Comment by cipchk** [comment]
hi everyone, will be coming in `ng add`

**Comment by daixuechao1** [comment]
亲测 不行 angular-cli v6.0.1  node v8.11.1 yarn v1.6.0

**Comment by matheusgarcez** [comment]
> ng new -c=@delon/cli my-app

```
C:\Users\mathe\AppData\Roaming\npm
+-- @angular/cli@6.0.1
+-- @delon/cli@1.0.0-beta.10
+-- @schematics/schematics@0.6.1
+-- npm@6.0.1
`-- typescript@2.8.3
```

Same there:
```
Schematic "ng-new" not found in collection "@delon/cli".
Error: Schematic "ng-new" not found in collection "@delon/cli".
    at SchematicEngine.createSchematic (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:23)
    at CollectionImpl.createSchematic (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\collection.js:12:29)
    at NodeWorkflow.execute (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\workflow\node-workflow.js:69:38)
    at Promise (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:140:22)
    at new Promise (<anonymous>)
    at NewCommand.runSchematic (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:139:16)
    at NewCommand.<anonymous> (C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:77:25)
    at Generator.next (<anonymous>)
    at C:\Users\mathe\AppData\Roaming\npm\node_modules\@angular\cli\commands\new.js:7:71
    at new Promise (<anonymous>)
```
